services:
  - type: web
    name: metal-web
    env: static
    rootDir: frontend
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
